### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by nk-coding**
see Readme

### CODE REVIEW

**Comment by ModellbahnFreak** [comment]
This was a triumph

**Comment by nk-coding** [comment]
I'm making a note here "Huge success"

**Comment by ModellbahnFreak** [comment]
Its hard to overstate my satisfaction

**Comment by nk-coding** [comment]
Aperture Science @spethso

**Comment by ModellbahnFreak** [comment]
We do what we must, because we can

**Pull request merged**
